### ISSUE TITLE
retorno do feed é undefined

### ISSUE THREAD

**Issue by nicollite** [fmsouza/nubank-api#10]
Estava testando a biblioteca e ao tentar utilizar o account.getFeed() está retornando undefined. 

Chequei a biblioteca de python para comparar os métodos e notei que falta a propriedade "data"  no caminho antes do viewer nesse caso.
Biblioteca em python:
![Sem título](https://user-images.githubusercontent.com/35429104/144886843-37b6725e-5007-4af8-9272-d66c9194f06a.png)

Come está:
![Sem título (1)](https://user-images.githubusercontent.com/35429104/144887143-c6fd9b58-ae62-471f-a6bf-65ba6244eded.png)

Felizmente a correção é simples e seria apenas adicionar o data no path pata ficar data?.data?.viewer?.savingsAccount?.feed

posso abrir um PR para concertar isso junto com as interfaces.

**Comment by nicollite** [comment]
Criei o PR aqui #11 , pode avalia-lo?

**Comment by matheuscouto** [comment]
Olá @nicollite, tinha feito o mesmo fix no PR https://github.com/fmsouza/nubank-api/pull/8 mas o @fmsouza ainda não chegou a olhar

**Comment by fmsouza** [comment]
@nicollite @matheuscouto desculpa a demora gente, ando bastante ocupado e não tive tempo de olhar antes. Acabei de dar merge no PR do @matheuscouto #8. Os módulos dentro de `lib` são os compilados estáticos gerados toda vez que eu publico uma nova versão do pacote NPM, não é pra mexer manualmente ali dentro.
