### ISSUE TITLE
Implementar filtro por data para feed e transaction

### ISSUE THREAD

**Issue by 13Nunes** [fmsouza/nubank-api#12]
Existe qualquer possibilidade de filtrar o retorno de card/feed e card/transation ?
Atualmente vem todos os registros desde a abertura da conta. 

É possível um filtro por data ?

**Comment by fmsouza** [comment]
@13Nunes sim, é possível. No entanto seria necessário implementar manualmente com Javascript, o que não vai ser o melhor dos mundos em termos de performance. A menos que a API permita filtragem dos resultados, o que no momento é desconhecido dado a API do Nubank é "fechada" e todo esse trabalho é feito por engenharia reversa.

Estou marcando essa issue como feature request para que possa ser implementado no futuro.

Caso queira ver o quanto a comunidade já descobriu sobre a API do Nubank, olha o [repositório Python](https://github.com/andreroggeri/pynubank/) do @andreroggeri.

**Comment by 13Nunes** [comment]
Pensando bem talvez seja melhor manter a library o mais pura possível.
Eu preferi fazer minha própria API no formato de adapter da sua:

https://github.com/13Nunes/nubank-dashboard

**Comment by andreroggeri** [comment]
Uma pessoa já encontrou uma query que retorna os dados da NuConta páginados, vcs podem dar uma olhada [aqui](https://github.com/andreroggeri/pynubank/pull/301/files)

**Comment by fmsouza** [comment]
A versão v3.1.0 que eu acabei de publicar implementa essa nova query paginada. Um exemplo pode ser encontrado aqui https://github.com/fmsouza/nubank-api/blob/master/examples/get-feed-paginated-cert.ts
