### ISSUE TITLE
está funcionando generate-certificate.ts ?

### ISSUE THREAD

**Issue by glira** [fmsouza/nubank-api#26]
Desculpe estou vindo de python não entendo bem node, estou recebendo erros ao tentar executar este código teste ai, gostaria de saber se está funcionando para obter o certificado porque o outro projeto python não está mais conseguindo obter o certificado e isso quebrou minhas pernas desde já agradeço qualquer ajuda.

**Comment by fmsouza** [comment]
@glira sim, a geração de certificado está funcionando. O que não está funcionando é o login com ele depois. Alguma coisa mudou na API e precisa ser mapeado pra ajustar aqui também.

Como esse projeto é basicamente um port do [projeto original em python](https://github.com/andreroggeri/pynubank/), estou observando o que acontece lá pra assim que ver e tiver tempo, atualizar aqui também.

Update: testei esse projeto local e tanto a geração de certificado quanto o login e as outras operações estão funcionando normalmente, conforme mencionado [aqui](https://github.com/andreroggeri/pynubank/issues/400#issuecomment-1589655408).
