### ISSUE TITLE
Como gerar o qrCode

### ISSUE THREAD

**Issue by renebizelli** [fmsouza/nubank-api#30]
Olá,

Podem me orientar em como gerar o qr-Code? Não ficou claro pra mim essa etapa.
Eu estou rodando o código, passando no parâmetro o uuid4() .. mas o retorno é 404, então percebei que deve ser um código válido.

obrigado

**Comment by fmsouza** [comment]
Olá @renebizelli!

**O QR code com o UUID pode ser gerado da forma que você preferir.** Pode ser algum gerador online pra você fazer a leitura com seu smartphone (no caso de um teste ou execução bem pessoal do código) ou até mesmo usando alguma lib da sua linguagem de preferência que gere como output um QR code.

A ideia aí é que para conseguir fazer o login, o Nubank precisa autorizar esse UUID do QR code através do app. Esse é o mesmo login que você faz quando entra no site do Nubank pra ver suas faturas online.

Portanto, o processo é:
- gere um UUID;
- use esse UUID pra gerar um QR code;
- vai no app do Nubank e leia esse QR code através da opção de acesso web;
- agora sim você pode prosseguir com a autenticação da lib usando cpf + senha + UUID (já autenticado)

Isso deverá te dar acesso às funções do Nubank no browser, que são bastante limitadas e só permitem acessar leituras do cartão de crédito, basicamente.

Espero ter ajudado!

**Comment by renebizelli** [comment]
consegui, amigo! Muito obrigado
